name: json_validator
description: Classes for working with json objects containing cross-dependencies
version: 0.5.0
homepage: https://github.com/ehrt74/dartlang-json-validator
author: ehrt74 <edouardtavinor@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
